### ISSUE TITLE
build Error missing required module 'libtdjson'

### ISSUE THREAD

**Issue by huang-ju** [leoMehlig/TDLib-iOS#1]
![image](https://user-images.githubusercontent.com/46550127/63376728-116d7000-c3c1-11e9-85bf-63a0a60ba2a2.png)

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/63377147-02d38880-c3c2-11e9-8794-78196768da6a.png)

**Comment by huang-ju** [comment]
How to solve this bug?

**Comment by arturiosRoom4** [comment]
Add swift search paths: $(PROJECT_DIR) - recursive

**Comment by huang-ju** [comment]
@arturiosRoom4  
Still have this problem.

![image](https://user-images.githubusercontent.com/46550127/63439670-1124b180-c461-11e9-8cc5-befccc1055d8.png)

**Comment by arturiosRoom4** [comment]
@huang-ju i solved this bug after including to copy phase libtdjson.dylib and add import paths (Swift compiler - search paths -> import paths)
![Screen Shot 2019-08-21 at 9 11 16 PM](https://user-images.githubusercontent.com/52455907/63456733-41b41d80-c458-11e9-8bb9-0a812e06b3ca.png)

**Comment by leoMehlig** [comment]
Copying the `.dylib` will result in a rejection when submitting to the App Store

**Comment by leoMehlig** [comment]
The problem might be (but I'm not sure) that there is some version mismatch.

**Comment by leoMehlig** [comment]
Also did you use Carthage?

**Comment by arturiosRoom4** [comment]
@leoMehlig my app based on Cordova, this make build process more difficult

**Comment by huang-ju** [comment]
solved this bug 
`` carthage update --no-use-binaries --use-ssh --platform iOS --cache-builds``

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/63584917-8662c480-c5d0-11e9-91b6-3278c403e7b6.png)
copy ``libtdcore.a`` to ``./Carthage/Checkouts/TDJSON/lib/``

**Comment by Pogosito** [comment]
@huang-ju Hi, BIG thank you I added only --no-use-binaries
