### ISSUE TITLE
SendMessageOptions parameters

### ISSUE THREAD

**Issue by digabriel** [leoMehlig/TDLib-iOS#16]
I'm trying to send a message to a bot, using the 1.6 version of the lib. The user sending the message have the `Last Seen & Online` privacy configuration set to only Contacts.

When creating the message I have to pass an options object of type `SendMessageOptions` that have a `schedulingState` parameter. What should I pass to this parameter? I'm using `sendWhenOnline` but this is working only when the user have the `Last Seen & Online` configuration set to `Everybody`. I think that the best approach here is to bo able to pass `nil` to `schedulingState`. This is how it works on the Android version of the TdLib.

Here's the code I'm using:

```
let input = InputMessageContent.inputMessageText(text: FormattedText(text: text,  entities: []), disableWebPagePreview: false,  clearDraft: true)
        
let options = SendMessageOptions(disableNotification: false,
                                         fromBackground: true,
                                         schedulingState: .sendWhenOnline)
        
let call = SendMessage(chatId: Int53(chatId),
                               replyToMessageId: 0,
                               options: options,
                               replyMarkup: nil,
                               inputMessageContent: input)
 ```

**Comment by digabriel** [comment]
@leoMehlig do you have any ideas to share on this?

Thank you!

**Comment by leoMehlig** [comment]
So sorry @digabriel! I've totally forgotten about this.

The problem was, that it wasn't clear to me, that all parameters are supposed to be optional. But the tdlib team explicitly stated that in an issue. So I changed the parser to make all parameters optional. I've already committed some time ago but forgot to prepare a release. I'm on it now and will let you know once the release is available.

Sorry again and thanks for reminding me!

**Comment by leoMehlig** [comment]
Done ✅ Can you check the [release](https://github.com/leoMehlig/TDLib-iOS/releases/tag/v1.6.2) and confirm it works.

**Comment by digabriel** [comment]
@leoMehlig with your update now is possible to pass a nil `options` param to the `SendMessage` request. This will work for my case, but I'll lose the ability to set the other options, like `disableNotification` and `fromBackground `, when sending a message.

What I was talking about is to be able to set only the `schedulingState` param of the `SendMessageOptions` to nil and continues to pass the `options` param to to `SendMessage`. This is how it works on the java version of tdlib.

Thank you for the attention.

**Comment by leoMehlig** [comment]
Apologies @digabriel. Can you please check the same release again. It should now have all the required parameters optional.

**Comment by digabriel** [comment]
Hi @leoMehlig. Everything works fine now. Thank you very much for your work.
