### ISSUE TITLE
missing required module 'libtdjson'

### ISSUE THREAD

**Issue by just-poster** [leoMehlig/TDLib-iOS#17]
Hi, I've been trying to test this library on a sample project from scratch. I used the carthage to install it according to instructions. My Xcode version is 11.6. 
I keep getting <unknown>:0: error: missing required module 'libtdjson' during compilation. 
I saw the related issue #9, but my Xcode is up to date. Are there any updated regarding this?

**Comment by just-poster** [comment]
I've come to the solution: just added TDLib and TDJSON manually to the project as frameworks. I built them using carthage with flags mentioned here:
https://github.com/leoMehlig/TDLib-iOS/issues/1#issuecomment-524256540
the only thing to worry about was, that libtdcore.a was inside checkouts for TDJSON.

**Comment by leoMehlig** [comment]
@VitaliyYarkun glad it works for you and sorry I didn't respond earlier.

Why are you worried about `libtdcore.a`, I normally excluded it from the git, because it was too big.

**Comment by just-poster** [comment]
@leoMehlig, thanks for your answer.
I had very limited time and couldn't totally investigate this issue, but when I was trying to solve it, I saw that if there was libtdcore.a in checkouts, then it worked. I suspected that TDLib has some dependencies on libtdcore.a and pointed this out. But as I said, I didn't investigate this from scratch:)

**Comment by sergeydi** [comment]
Where to get libtdcore.a?
