### ISSUE TITLE
<Update?> Enum is expected. 

### ISSUE THREAD

**Issue by arturiosRoom4** [leoMehlig/TDLib-iOS#4]
Unable to use switch construction with this type on UpdateStream subscription.
Maybe I'm doing something wrong, I'm a beginner in Swift
![Screen Shot 2019-08-27 at 6 52 24 PM](https://user-images.githubusercontent.com/52455907/63787155-056f3a00-c8fc-11e9-9fa8-9e9b357028ed.png)

**Comment by leoMehlig** [comment]
Please take a look at the [docs](https://leomehlig.com/TDLib-iOS/Enums/Update.html).
Also the event is an optional, because in the beginning there is no event. This means you need to do something like that (if you don't care about the new message):
```Swift
switch event {
   case .newMessage?:
       print(event)
}
```

**Comment by arturiosRoom4** [comment]
I tried to do as in your example. I got this error:

> The compiler is unable to check that this switch is exhaustive in reasonable time

**Comment by arturiosRoom4** [comment]
Solved, after add 'default' case. Thanks!

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/63945701-5de23b00-caa6-11e9-9755-96235d51ab5c.png)
How to parse data ？
