### ISSUE TITLE
How to parse data ？

### ISSUE THREAD

**Issue by huang-ju** [leoMehlig/TDLib-iOS#5]
![image](https://user-images.githubusercontent.com/46550127/63948202-d77c2800-caaa-11e9-866f-b67f812762ca.png)
How to parse data ？

**Comment by leoMehlig** [comment]
The enum already has associated values with all the data.

**Comment by leoMehlig** [comment]
https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

**Comment by huang-ju** [comment]
Sorry, I'm a beginner in Swift
I don't understand

![image](https://user-images.githubusercontent.com/46550127/64012413-3a73ca80-cb50-11e9-94a9-4d2c10bdf9e7.png)

I want to get messageText.text

what should I do ?

**Comment by leoMehlig** [comment]
You can do:
```Swift
switch event {
   case .newMessage(let message)?:
       print(message)
   default:
       break
}
```
