### ISSUE TITLE
The login device is wrong.  

### ISSUE THREAD

**Issue by huang-ju** [leoMehlig/TDLib-iOS#6]
![image](https://user-images.githubusercontent.com/46550127/65754394-8d3aa500-e143-11e9-980b-1411785d35ac.png)

I am using the iPhone to log in, but the Telegram shows that I am Android.

**Comment by leoMehlig** [comment]
You can set the device in the [TdLibParamemters](https://leomehlig.com/TDLib-iOS/Structs/TdlibParameters.html#/s:5TDLib15TdlibParametersV11deviceModelSSvp) you pass to the `Coordinater` initialiser.

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/65772873-b839ee80-e16d-11e9-945d-0c23e906fe36.png)

Not the default iphone ？

**Comment by leoMehlig** [comment]
Yes, that's the default. But try settings something else. I assume that the login with device android was performed from a different device.

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/66700448-d2a1c980-ed22-11e9-9fb6-778ac47f760a.png)

![image](https://user-images.githubusercontent.com/46550127/66700453-f402b580-ed22-11e9-9d3f-0d8212932470.png)

Why is it wrong? I want to set deviceModel

**Comment by huang-ju** [comment]
@leoMehlig

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/66705567-04cf1d80-ed5b-11e9-8fb3-d4433a726dab.png)

return ``Error(code: 400, message: "File \"/td.binlog\" can\'t be opened/created for reading and writing")``
