### ISSUE TITLE
How to register an account? Registered account did not send SMS

### ISSUE THREAD

**Issue by huang-ju** [leoMehlig/TDLib-iOS#7]
account did not send SMS。

**Comment by leoMehlig** [comment]
Can you send your example code?

**Comment by huang-ju** [comment]
I send my Phonenumber
``self.coordinator.send(SetAuthenticationPhoneNumber(phoneNumber: phone, allowFlashCall: true, isCurrentPhoneNumber: true))``

return

``value(TDLib.AuthorizationState.waitCode(isRegistered: false, termsOfService: Optional(TDLib.TermsOfService(text: TDLib.FormattedText(text: "By signing up for Telegram, you agree not to:\n\n- Use our service to send spam or scam users.\n- Promote violence on publicly viewable Telegram bots, groups or channels.\n- Post pornographic content on publicly viewable Telegram bots, groups or channels.\n\nWe reserve the right to update these Terms of Service later.", entities: []), minUserAge: 0, showPopup: false)), codeInfo: TDLib.AuthenticationCodeInfo(phoneNumber: "+8615625064148", type: TDLib.AuthenticationCodeType.sms(length: 0), nextType: nil, timeout: 0)))``

sms ``length`` is 0 and I didn't receive the sms

**Comment by leoMehlig** [comment]
I just saw that the api wrapper is out of date.  I'm will build a new version now and then it should work.

**Comment by huang-ju** [comment]
Thank you

**Comment by leoMehlig** [comment]
Sorry for the delay. I'm having problems building the v1.5 `tdlib`. I will keep trying and update asap.

**Comment by leoMehlig** [comment]
I currently get errors when building v1.5.0. I've created an issue on [tdlib-737](https://github.com/tdlib/td/issues/737)

**Comment by leoMehlig** [comment]
I just released v1.5. Can you check again with the new version.
