### ISSUE TITLE
I want to set SetTdlibParameters  

### ISSUE THREAD

**Issue by huang-ju** [leoMehlig/TDLib-iOS#8]
![66700448-d2a1c980-ed22-11e9-9fb6-778ac47f760a](https://user-images.githubusercontent.com/46550127/66727441-d2641400-ee71-11e9-8ff8-a7f095e977fd.png)

![66700453-f402b580-ed22-11e9-9d3f-0d8212932470](https://user-images.githubusercontent.com/46550127/66727442-d42dd780-ee71-11e9-95e0-fccf44e7fe04.png)

Initialize settings SetTdlibParameters

or

![66705567-04cf1d80-ed5b-11e9-8fb3-d4433a726dab](https://user-images.githubusercontent.com/46550127/66727474-00e1ef00-ee72-11e9-8696-09405e34632a.png)

``coordinator.send(SetTdlibParameters())``

return Error(code: 400, message: "File \"/td.binlog\" can\'t be opened/created for reading and writing")
 
Why is it wrong? I want to set deviceModel

**Comment by leoMehlig** [comment]
Can you supply a path for `databaseDirectory` and `fileDirectory`. The default one from `TDLib` probably does not work on iOS.

**Comment by leoMehlig** [comment]
[This](https://github.com/leoMehlig/TDLib-iOS/blob/4349af7f22d8ae622f5f272396be4e8ac066d227/TDLib/Coordinator.swift#L79) is the current default when not setting parameters.

**Comment by huang-ju** [comment]
The default ``deviceModel`` does not take effect。

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/66771870-f7966800-eeed-11e9-8ddc-66a0d3c9df0c.png)

![image](https://user-images.githubusercontent.com/46550127/66771881-febd7600-eeed-11e9-88b6-e825a400a472.png)

How can I set ``deviceModel`` to ``iphone``?

**Comment by huang-ju** [comment]
Can you send example code?

**Comment by huang-ju** [comment]
I tried a lot of methods but failed。

**Comment by leoMehlig** [comment]
I currently get errors when building v1.5.0. I've created an issue on [tdlib-737](https://github.com/tdlib/td/issues/737)

**Comment by leoMehlig** [comment]
Can you check in the logs if the correct `json` is send? If that is the case you would have to open an issue with [tdlib](https://github.com/tdlib/td/)

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/66990262-7101a680-f0f8-11e9-9263-9118560b393d.png)

I only know that I sent it successfully.

**Comment by leoMehlig** [comment]
I just released v1.5. Can you check again with the new version.
Otherwise, could you provide a small sample project...
