### ISSUE TITLE
missing required module 'libtdjson'

### ISSUE THREAD

**Issue by profugocanis** [leoMehlig/TDLib-iOS#9]
Hello
"missing required module 'libtdjson'" pops up after adding to the project
thank

**Comment by leoMehlig** [comment]
How did you add the project?

**Comment by profugocanis** [comment]
through cartfile
<img width="868" alt="Снимок экрана 2019-10-31 в 16 34 19" src="https://user-images.githubusercontent.com/40450021/67956182-59e4ad80-fbfc-11e9-9248-5a9308670c64.png">

**Comment by profugocanis** [comment]
![Uploading Снимок экрана 2019-10-31 в 16.37.03.png…]()

**Comment by profugocanis** [comment]
it used to work, but after the update it stopped

**Comment by leoMehlig** [comment]
Please try to delete the Carthage folder and run `carthage bootstrap` again.

**Comment by profugocanis** [comment]
I already tried it
created a new project, added Carthage (carthage update - platform iOS) the same thing comes out
TDJSON separately downloaded

**Comment by leoMehlig** [comment]
Can you upload that sample project?

**Comment by profugocanis** [comment]
Thank you so much, I updated xcode to version 11.2 and it worked

**Comment by mirasaujan** [comment]
I have the same issue. Using Carthage. Xcode version 11.3.1. When I open TDJSON I get this
![image](https://user-images.githubusercontent.com/16839294/81717294-2bde0100-949c-11ea-9f0a-6a8d84a84c82.png)
